import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="vV70oydhHyHlTJtFSqdZiX6it9v1Nv_iaySUAbv0z6w"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
